name: Deploy to VPS

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Start ssh-agent and add key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add droplet host key to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -p 22 ${{ secrets.DROPLET_HOST }} >> ~/.ssh/known_hosts

      - name: Ensure remote directory exists
        run: ssh "${{ secrets.DROPLET_USER }}@${{ secrets.DROPLET_HOST }}" "mkdir -p '${{ secrets.REMOTE_DIR }}'"

      - name: Rsync repo to droplet (exclude local-only files)
        run: |
          rsync -az --delete \
            --exclude '.env' \
            --exclude 'node_modules' \
            --exclude '.git' \
            --exclude '.github' \
            ./  "${{ secrets.DROPLET_USER }}@${{ secrets.DROPLET_HOST }}:${{ secrets.REMOTE_DIR }}/"

      - name: Install deps & reload PM2 on VPS
        run: >
          ssh "${{ secrets.DROPLET_USER }}@${{ secrets.DROPLET_HOST }}"
          "bash -lc 'set -euo pipefail;
            cd \"${{ secrets.REMOTE_DIR }}\";
            export NPM_CONFIG_FUND=false;
            npm ci --omit=dev;
            pm2 describe inventory-picker-socket >/dev/null 2>&1
              && pm2 reload inventory-picker-socket --update-env
              || pm2 start index.js --name inventory-picker-socket;
            pm2 save'"